services:
  web:
    image: ui-setup-web-dev
    working_dir: /repo/apps/web
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: '1'
      WATCHPACK_POLLING: 'true'
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: '250'
    volumes:
      - ./:/repo
      - /repo/node_modules
      - /repo/apps/web/node_modules
      - /repo/apps/web/.next
